# Generated by Django 4.0 on 2022-06-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0002_draft_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='image',
            field=models.ImageField(upload_to='category_images'),
        ),
    ]
