# Generated by Django 4.0 on 2022-06-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0004_alter_category_image_alter_draft_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
