# Generated by Django 4.0 on 2022-06-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('draft_app', '0006_remove_draft_category_draft_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Draft',
            new_name='Termin',
        ),
    ]
