# Generated by Django 4.0 on 2022-06-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0009_imageblock_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='termin',
            name='image',
            field=models.ImageField(upload_to='draft_images'),
        ),
    ]
