# Generated by Django 4.0 on 2022-06-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0010_textblock_title_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textblock',
            old_name='title',
            new_name='header',
        ),
        migrations.AddField(
            model_name='post',
            name='posttype',
            field=models.CharField(choices=[('post', 'post'), ('tool', 'tool')], default='post', max_length=20),
        ),
    ]
