# Generated by Django 4.0 on 2022-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0011_rename_title_textblock_header_post_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(),
        ),
    ]
