# Generated by Django 4.0 on 2022-07-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0013_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='draft_images'),
        ),
    ]
