# Generated by Django 4.0 on 2022-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0014_alter_termin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
