# Generated by Django 4.0 on 2022-07-16 12:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0015_alter_termin_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termin',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
